kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: threescale-secrets-manager
rules:
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - secrets
