kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: threescale-operator-manage-secrets-global
subjects:
  - kind: ServiceAccount
    name: 3scale-operator
    namespace: threescale
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: threescale-secrets-manager