apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
  name: threescale-development-tenant
spec:
  email: dev@example.openshift.com
  masterCredentialsRef:
    name: system-seed
  organizationName: development
  passwordCredentialsRef:
    name: tenant-admin-secret
  systemMasterUrl: 'https://master.apps.cluster-wpdbw.wpdbw.sandbox265.opentlc.com'
  tenantSecretRef:
    name: dev-tenant-secret
    namespace: threescale
  username: admin